apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-lego
    heritage: Tiller
  name: kube-lego2-kube-lego
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: kube-lego
    chart: kube-lego-0.3.0
    heritage: Tiller
    release: kube-lego2
  name: kube-lego2-kube-lego
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - delete
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - update
  - create
  - list
  - patch
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - secrets
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-lego
    chart: kube-lego-0.3.0
    heritage: Tiller
    release: kube-lego2
  name: kube-lego2-kube-lego
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-lego2-kube-lego
subjects:
- kind: ServiceAccount
  name: kube-lego2-kube-lego
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-lego
    chart: kube-lego-0.3.0
    heritage: Tiller
    release: kube-lego2
  name: kube-lego2-kube-lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-lego
        release: kube-lego2
    spec:
      serviceAccountName: kube-lego2-kube-lego
      containers:
      - name: kube-lego
        image: "jetstack/kube-lego:0.1.5"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: LEGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # admin@rehive.com
        - name: "LEGO_EMAIL"
          value: "admin@rehive.com"
        - name: "LEGO_PORT"
          value: "8080"
        - name: "LEGO_URL"
          value: "https://acme-v01.api.letsencrypt.org/directory"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          {}